# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Tetris

steps:
- script: |
    cd ..
    mkdir saqwel
    cd saqwel
    git clone https://$(GITHUB_REPOSITORY_USERNAME):$(GITHUB_REPOSITORY_PASSWORD)github.com/saqwel/tetris.git
    ls -la
    echo "Clone"
    cd ..
    git clone https://$(AZURE_REPOSITORY_USERNAME):$(AZURE_REPOSITORY_PASSWORD)@dev.azure.com/KonstantinKostin/ADOLab/_git/tetris
    cat tetris/.git/config
    echo "Copy"
    rsync -av --progress s/* tetris --exclude .git --checksum
    cat tetris/.git/config
    cd tetris
    echo "Push"
    git config --global user.name "Konstantin Kostin"
    git config --global user.email "konstantin_kostin@epam.com"
    git add -A
    git commit -m 'Automatic update'
    git push
  displayName: 'Clone repository'
