# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Tetris

steps:
- script: |
    ls -l
    cd ..
    ls -l
    echo "Clone"
    git clone https://$(AZURE_REPOSITORY_USERNAME):$(AZURE_REPOSITORY_PASSWORD)@dev.azure.com/KonstantinKostin/ADOLab/_git/tetris
    ls -l
    echo "Copy"
    rsync -av --progress s/* tetris --exclude .git --checksum
    #yes | cp -rf s/* tetris
    cd tetris
    ls -l
    echo "Push"
    git push
  displayName: 'Clone repository'
