# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: ls -l
  displayName: 'Get content'

- script: |
    cd ..
    ls -l
    git clone https://KonstantinKostin@dev.azure.com/KonstantinKostin/ADOLab/_git/tetris
  displayName: 'Clone repository'
